remote_theme: just-the-docs/just-the-docs

# Site settings
title: Just the Docs
description: A Jekyll theme for documentation
baseurl: "/dev-jambin" # the subpath of your site, e.g. /blog
url: "https://dev-jambin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: "dark"
search_enabled: false
