title: GreenBin
description: 말은 쉽지. 코드를 보여줘!
theme: "just-the-docs"

url: 'https://dev-jmabin.github.io'

aux_links:
  "dev-jambin GitHub": "https://dev-jambin.github.io"

callouts :
  highlight:
    color: green