title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: "just-the-docs"

url: 'https://dev-jmabin.github.io'

aux_links:
  "dev-jambin GitHub": "https://dev-jambin.github.io"

